Add explanation for decision tree
bfortuner/ml-glossary pull request #109
Opened 2020-09-16 05:06 UTC by xiaoye-hua

@bfortuner  Hi. Brendan. I've add  an explanation of decision tree including ID3，C4.5 and CART. Please help me to review and merge these changes.

2020-09-16 05:10 UTC, ivanistheone commented on docs/classification_algos.rst
> +ID3 creates a multiway tree. For each node, it try to find the categorical feature that will yield the largest information gain for the target variable.
it trie**s**

2020-09-16 05:11 UTC, ivanistheone commented on docs/classification_algos.rst
> +The main differences are shown in the follow table:
follow --> following

2020-09-16 05:13 UTC, ivanistheone commented on docs/classification_algos.rst
> +For CART algorithm, when constructing the binary tree, it will try search for the feature and threshold that will yield the largest gain or the least impurity. The split criterion is a combination of
For CART algorithm, when constructing the binary tree, **it** will try search for
-->
**The** CART algorithm, when constructing the binary tree, will try search**ing** for

2020-09-16 05:15 UTC, ivanistheone commented
seems to be also a .pyc file not needed, see `code/decision_tree/__pycache__/decision_tree_base.cpython-36.pyc`

2020-09-16 05:16 UTC, ivanistheone requested changes
I made some minor suggestions for typo fixes. Code look good, though I haven't tried running it.

2020-09-17 03:51 UTC, xiaoye-hua commented
> I made some minor suggestions for typo fixes. Code look good, though I haven't tried running it.

@ivanistheone Hi. Thank you for your review. I've correct these typo errors and removed the unrelated file.

2020-12-24 18:21 UTC, merged